(()=>{
const canvas=document.getElementById('game3d'),ctx=canvas.getContext('2d');
const startBtn=document.getElementById('start3d'),scoreEl=document.getElementById('score3d'),statusEl=document.getElementById('status3d');
let W=1200,H=600,dpr=1,running=false,score=0,health=3,wave=1,time=0,spawnTimer=0,shotTimer=0,rapidTimer=0,spreadTimer=0,shake=0;
let targets=[],shots=[],sparks=[],keys={},aim={x:600,y:260},playerX=0,targetX=0;
const BAD=['apple','orange','grapes','poo'],GOOD=['burger','pizza','candy'];
const colors={apple:'#ec4c45',orange:'#ff982f',grapes:'#8e62d9',poo:'#78401f',burger:'#efa83f',pizza:'#ffd34d',candy:'#f46ea6'};
function resize(){const r=canvas.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);W=r.width;H=Math.max(440,r.height);canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);aim.x=W/2;aim.y=H*.38}
addEventListener('resize',resize);resize();
function project(x,y,z){const f=Math.min(W,H)*.92/(z+2);return{x:W/2+(x-playerX*.18)*f,y:H*.34+(y+1.55)*f,s:f}}
function reset(){running=true;score=0;health=3;wave=1;time=0;spawnTimer=.3;shotTimer=0;rapidTimer=0;spreadTimer=0;targets=[];shots=[];sparks=[];playerX=targetX=0;scoreEl.textContent='0000';statusEl.textContent='HEALTH 3';startBtn.textContent='RESTART SHOOTER'}
function spawn(){const badChance=Math.min(.72,.52+time/180);const good=Math.random()>badChance;const type=(good?GOOD:BAD)[Math.floor(Math.random()*(good?GOOD.length:BAD.length))];targets.push({type,bad:!good,x:(Math.random()-.5)*12,y:(Math.random()-.5)*3.8,z:48+Math.random()*8,hp:type==='poo'&&wave>3?2:1,spin:Math.random()*6,vx:(Math.random()-.5)*.7})}
function fire(){if(!running||shotTimer>0)return;shotTimer=rapidTimer>0?.095:.22;const angles=spreadTimer>0?[-.11,0,.11]:[0];for(const a of angles){const nx=(aim.x-W/2)/W*12+a*12,ny=(aim.y-H*.34)/H*7;shots.push({x:playerX*.18,y:1.2,z:2,vx:(nx-playerX*.18)/18,vy:(ny-1.2)/18,vz:42,life:1.1})}}
function burst(x,y,z,color,count=12){for(let i=0;i<count;i++)sparks.push({x,y,z,vx:(Math.random()-.5)*5,vy:(Math.random()-.5)*5,vz:(Math.random()-.5)*5,life:.45+Math.random()*.45,color})}
function hitTarget(i){const t=targets[i];t.hp--;burst(t.x,t.y,t.z,colors[t.type],t.bad?16:22);if(t.hp>0){shake=5;return}if(t.bad){score+=t.type==='poo'?30:20;statusEl.textContent=t.type==='poo'?'POO DESTROYED':'VITAMIN DESTROYED'}else if(t.type==='burger'){health=Math.min(5,health+1);score+=10;statusEl.textContent='BURGER ARMOUR +1'}else if(t.type==='pizza'){spreadTimer=8;score+=15;statusEl.textContent='PIZZA SPREAD SHOT'}else{rapidTimer=8;score+=20;statusEl.textContent='CANDY RAPID FIRE'}scoreEl.textContent=String(score).padStart(4,'0');targets.splice(i,1);shake=7}
function damage(type){health--;shake=16;statusEl.textContent=type==='poo'?'POO BREACHED DEFENCES':`${type.toUpperCase()} VITAMINS HIT`;if(health<=0){running=false;statusEl.textContent='COOPER COMPROMISED';startBtn.textContent='TRY SHOOTER AGAIN'}else setTimeout(()=>{if(running)statusEl.textContent=`HEALTH ${health}`},650)}
function update(dt){if(!running)return;time+=dt;wave=1+Math.floor(time/18);shotTimer=Math.max(0,shotTimer-dt);rapidTimer=Math.max(0,rapidTimer-dt);spreadTimer=Math.max(0,spreadTimer-dt);spawnTimer-=dt;shake*=Math.pow(.03,dt);if(spawnTimer<=0){spawn();spawnTimer=Math.max(.25,.82-time*.006)*(Math.random()*.55+.7)}
if(keys.ArrowLeft||keys.a||keys.A)targetX-=dt*9;if(keys.ArrowRight||keys.d||keys.D)targetX+=dt*9;targetX=Math.max(-5.5,Math.min(5.5,targetX));playerX+=(targetX-playerX)*Math.min(1,dt*9);
for(let i=shots.length-1;i>=0;i--){const s=shots[i];s.x+=s.vx*s.vz*dt;s.y+=s.vy*s.vz*dt;s.z+=s.vz*dt;s.life-=dt;let removed=false;for(let j=targets.length-1;j>=0;j--){const t=targets[j],dx=s.x-t.x,dy=s.y-t.y,dz=s.z-t.z;if(dx*dx+dy*dy<1.3&&Math.abs(dz)<2.4){hitTarget(j);shots.splice(i,1);removed=true;break}}if(!removed&&(s.life<=0||s.z>60))shots.splice(i,1)}
for(let i=targets.length-1;i>=0;i--){const t=targets[i];t.z-=dt*(8.7+wave*.72);t.spin+=dt*(1.1+t.vx);t.x+=Math.sin(time*1.4+t.spin)*dt*t.vx;if(t.z<2.2){if(t.bad)damage(t.type);else{score=Math.max(0,score-5);scoreEl.textContent=String(score).padStart(4,'0');statusEl.textContent='MISSED JUNK FOOD'}targets.splice(i,1)}}
for(const p of sparks){p.x+=p.vx*dt;p.y+=p.vy*dt;p.z+=p.vz*dt;p.life-=dt}sparks=sparks.filter(p=>p.life>0)}
function pathItem(type,s){ctx.beginPath();if(type==='pizza'){ctx.moveTo(0,-s*.58);ctx.lineTo(s*.58,s*.48);ctx.lineTo(-s*.58,s*.48);ctx.closePath()}else if(type==='candy'){ctx.roundRect(-s*.42,-s*.3,s*.84,s*.6,s*.15);ctx.moveTo(-s*.42,0);ctx.lineTo(-s*.72,-s*.25);ctx.lineTo(-s*.72,s*.25);ctx.closePath();ctx.moveTo(s*.42,0);ctx.lineTo(s*.72,-s*.25);ctx.lineTo(s*.72,s*.25);ctx.closePath()}else if(type==='poo'){ctx.arc(0,s*.16,s*.48,Math.PI,0);ctx.arc(-s*.23,0,s*.32,Math.PI,0);ctx.arc(s*.23,0,s*.32,Math.PI,0);ctx.lineTo(s*.48,s*.42);ctx.lineTo(-s*.48,s*.42);ctx.closePath()}else if(type==='grapes'){for(let y=-1;y<=1;y++)for(let x=-1;x<=1;x++){ctx.moveTo(x*s*.25+s*.18,y*s*.22);ctx.arc(x*s*.25,y*s*.22,s*.21,0,7)}}else if(type==='orange'){ctx.arc(0,0,s*.5,0,7)}else ctx.roundRect(-s*.5,-s*.38,s,s*.76,s*.24)}
function drawItem(t,p){const s=Math.max(10,p.s*.78);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(t.spin);ctx.shadowColor='#000b';ctx.shadowBlur=Math.min(28,s*.3);ctx.fillStyle=colors[t.type];ctx.strokeStyle=t.bad?'#ffea6b':'#111';ctx.lineWidth=Math.max(2,s*.055);pathItem(t.type,s);ctx.fill();ctx.stroke();if(t.bad){ctx.strokeStyle='#fff';ctx.lineWidth=Math.max(1,s*.035);ctx.beginPath();ctx.moveTo(-s*.16,-s*.12);ctx.lineTo(-s*.04,0);ctx.moveTo(s*.16,-s*.12);ctx.lineTo(s*.04,0);ctx.stroke()}ctx.restore()}
function drawBackground(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#071126');g.addColorStop(.48,'#4d286d');g.addColorStop(.485,'#15151d');g.addColorStop(1,'#020204');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.strokeStyle='#dfff3948';ctx.lineWidth=1;for(let z=4;z<55;z+=4){const a=project(-11,1,z),b=project(11,1,z);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}for(let x=-12;x<=12;x+=2){const a=project(x,1,3),b=project(x,1,55);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}ctx.fillStyle='#dfff39';for(let i=0;i<50;i++){let z=(i*7-time*8)%58;if(z<2)z+=58;const p=project((i%2?1:-1)*(8+i%4),-1.3+(i%5)*.5,z);ctx.fillRect(p.x-1.5,p.y-1.5,3,3)}}
function drawWeapon(){const x=W/2+playerX*W*.052,y=H*.88;ctx.save();ctx.translate(x,y);ctx.fillStyle='#252936';ctx.strokeStyle='#dfff39';ctx.lineWidth=3;ctx.beginPath();ctx.roundRect(-42,-18,84,48,12);ctx.fill();ctx.stroke();ctx.fillStyle='#ffcc68';ctx.beginPath();ctx.roundRect(-25,-62,50,46,18);ctx.fill();ctx.strokeStyle='#111';ctx.stroke();ctx.fillStyle='#111';ctx.beginPath();ctx.arc(-9,-45,3,0,7);ctx.arc(9,-45,3,0,7);ctx.fill();ctx.fillStyle='#dfff39';ctx.fillRect(-8,-83,16,28);ctx.restore()}
function drawHud(){ctx.fillStyle='#fff';ctx.font='700 13px Space Mono, monospace';ctx.fillText(`WAVE ${wave}`,18,27);ctx.fillText(`HEALTH ${'■'.repeat(health)}${'□'.repeat(Math.max(0,5-health))}`,18,49);if(rapidTimer>0)ctx.fillText(`RAPID ${rapidTimer.toFixed(1)}s`,18,71);if(spreadTimer>0)ctx.fillText(`SPREAD ${spreadTimer.toFixed(1)}s`,18,93);ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(aim.x,aim.y,17,0,7);ctx.moveTo(aim.x-27,aim.y);ctx.lineTo(aim.x-8,aim.y);ctx.moveTo(aim.x+8,aim.y);ctx.lineTo(aim.x+27,aim.y);ctx.moveTo(aim.x,aim.y-27);ctx.lineTo(aim.x,aim.y-8);ctx.moveTo(aim.x,aim.y+8);ctx.lineTo(aim.x,aim.y+27);ctx.stroke()}
function draw(){ctx.save();ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);drawBackground();targets.slice().sort((a,b)=>b.z-a.z).forEach(t=>drawItem(t,project(t.x,t.y,t.z)));for(const s of shots){const p=project(s.x,s.y,s.z);ctx.fillStyle='#dfff39';ctx.shadowColor='#dfff39';ctx.shadowBlur=16;ctx.beginPath();ctx.arc(p.x,p.y,Math.max(2,p.s*.05),0,7);ctx.fill()}for(const p0 of sparks){const p=project(p0.x,p0.y,Math.max(2,p0.z));ctx.globalAlpha=Math.max(0,p0.life);ctx.fillStyle=p0.color;ctx.fillRect(p.x-3,p.y-3,6,6);ctx.globalAlpha=1}drawWeapon();drawHud();ctx.restore();if(!running){ctx.fillStyle='#0009';ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='700 30px Fredoka, sans-serif';ctx.fillText(health<=0?'COOPER HAS BEEN COMPROMISED':'VITAMIN DEFENCE SHOOTER',W/2,H*.43);ctx.font='700 14px Space Mono, monospace';ctx.fillText('AIM WITH MOUSE OR TOUCH • FIRE WITH CLICK OR SPACE',W/2,H*.5);ctx.textAlign='left'}}
let last=performance.now();function loop(now){const dt=Math.min((now-last)/1000,.034);last=now;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
addEventListener('keydown',e=>{keys[e.key]=true;if(e.code==='Space'){e.preventDefault();fire()}});addEventListener('keyup',e=>keys[e.key]=false);
function point(e){const r=canvas.getBoundingClientRect(),touch=e.touches?.[0];aim.x=(touch?.clientX??e.clientX)-r.left;aim.y=(touch?.clientY??e.clientY)-r.top}
canvas.addEventListener('pointermove',point);canvas.addEventListener('pointerdown',e=>{point(e);fire()});canvas.addEventListener('touchmove',e=>{e.preventDefault();point(e)},{passive:false});canvas.addEventListener('touchstart',e=>{e.preventDefault();point(e);fire()},{passive:false});startBtn.onclick=reset;
})();